### PR TITLE
add slides and link to slides for ch.6

### PR DESCRIPTION
**Pull request by novica**

### CODE REVIEW

**Review by tanho63 — COMMENTED** [review]
Do you have the RMD itself? :)

**Comment by novica** [comment]
Yes. I have the RMD but didn't see where to upload it?

**Comment by tanho63** [comment]
Same folder as the html file :)

**Review by tanho63 — APPROVED** [review]
lgtm

**Comment by novica** [comment]
TIL that there is LGTM. :)

**Pull request merged**
