### PR TITLE
adding initial notes and docs

### PR DESCRIPTION
**Pull request by MayaGans**
Adding:

- Exercise Folder
- QandA Folder
- Presentation Folder
- README

### CODE REVIEW

**Comment by russHyde** [comment]
Would you be able to add `.Rproj.user`, `.Rhistory` and `**/.DS_Store` to the `.gitignore` file, please.

**Comment by MayaGans** [comment]
Hi @russHyde I believe I've done this [and I also hopefully removed all cached files](https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore)

TBH I have never added files to a .gitignore! 😬Please advise if there's anything else I need to do. Thanks!

**Comment by russHyde** [comment]
Thanks. The user-specific and OS-specific files can cause problems on other-people's computers (and Rhistory is updated each time you work on a project in R, so keeping it under version control leads to git-bloat). Adding them to .gitignore means that they won't be stored in version control.

You could clone this PR to a fresh directory if you wanted to check if the files are no longer followed by git

**Comment by MayaGans** [comment]
Ah ha! Alright I tested locally and it looks like I did it correctly? 🤞

**Comment by tanho63** [comment]
Could try the default R gitignore file in the future :) https://github.com/github/gitignore/blob/master/R.gitignore

**Comment by MayaGans** [comment]
Hey @russHyde -- made some minor updates to the slide template if people want to use it for presentations. Can you check and merge prior to this weeks meeting [Thursday] please? 🙏

**Comment by russHyde** [comment]
Hi. I've knitted the html documents for this and it all looks fine. The one thing I would question is the use of the xaringanthemer package, simply because it's not on CRAN yet. But happy for it to be merged anyway.

**Pull request merged**
