### PR TITLE
Bookdown QandA

### PR DESCRIPTION
**Pull request by MayaGans**
So this is kind of experimental... 

I added another R Project inside the QandA folder so we can build the book and structured the files so that 02 is chapter 2, 03 chapter 3 etc. It's the same as having individual markdowns per chapter but now it's all tied together in a book that we can eventually tie to the website somehow? 

What do you think?

### CODE REVIEW

**Comment by tanho63** [comment]
What purpose does the current 'Rproj' file serve right now? 

Also, I think Exercises folder hasn't seen much use

**Comment by MayaGans** [comment]
So this is where I admit that I just stole yihui's bookdown template, I'm sure there's a bunch of stuff in there we can triage. 

As per Exercises: I was thinking we use that folder for proposed answers for the questions that have yet to be answered in the solutions manual (so far all the questions have answers) -- and we can eventually when happy submit those answers as PRs to the manual? Just a thought. Maybe we'll leave it a little longer and see if it get used.

**Comment by MayaGans** [comment]
@tanho63 as per RProj..... this is super noob but if you open that project you get the "build" button to build the book 😬probably not necessary but I don't know how else you'd build - I imagine there's some command we can use. Feel free to pull down this branch and clean her up! 

Screen Shot 2020-04-30 at 10 43 36 AM

**Comment by MayaGans** [comment]
Hey @tanho63, I made more changes to further customize our files from Yihui's demo files so I *think* this should be mergable now since everyone was on board with changing to a bookdown format? Thoughts? Anything else I need to clean up?

**Comment by tanho63** [comment]
Looks like one of your builds made `_book` and `images` folders at the top level? (Maybe rename data to Data to keep consistent naming structures?)

**Pull request merged**
