### PR TITLE
Chapter 5 Prep

### PR DESCRIPTION
**Pull request by MayaGans**
Adding my questions in preparation for this weeks meeting, as well as adding some questions and answers from the Slack channel (I can make each question its own PR to make these pushes smaller in the future - sorry!)

### CODE REVIEW

**Comment by tanho63** [comment]
Probably easier not to deal with merge commits if you're doing one big Q/A file. would maybe suggest it if we were doing a separate QA for each chapter?

**Comment by MayaGans** [comment]
Innnnnteresting.... I can divide each chapter into its own markdown file then combine them in like a bookdown maybe?

**Comment by tanho63** [comment]
Yeah, that might make sense! Also makes it easier to skim just the one page to help prep for the meeting?

**Comment by MayaGans** [comment]
Cool - can we merge this, then open an issue to change the file structure?

**Pull request merged**
