### PR TITLE
adding new control flow image

### PR DESCRIPTION
**Pull request by MayaGans**

### CODE REVIEW

**Comment by gadenbuie** [comment]
Hey @MayaGans I really like this flow chart! (I saw it in Slack but I'm better at dropping in on GitHub issues.) One thing that I've been thinking about since I saw it is `ifelse()`, which is a bit different from the other control flow structures because it's vectorized.

I made up a [sketch in Figma](https://www.figma.com/file/KY6Mk1xxNXfGKK0OQhHPGk/Untitled?node-id=0%3A1) that shows how I tend to think about `ifelse()`, maybe it's helpful.

Frame 1

**Comment by MayaGans** [comment]
I LOVE THIS @gadenbuie !!! The graphics I made are definitely a WIP, but also its super helpful to high level compare/contrast.... and also identify gaps in my mental model (like how I completely ignored how ifelse is vectorized!) Thank you!

**Comment by gadenbuie** [comment]
Thanks! My sketch is also very WIP 😉 

Here's something to try with your mental model of `ifelse()`

```r
ifelse(c(TRUE, FALSE, TRUE), 1:2, 3)
```

Honestly, `ifelse()` is *weird*. Try this too

```r
ifelse(c(TRUE, FALSE, TRUE), 1:10, 3)
```

**Comment by MayaGans** [comment]
To borrow from your schematic....

Screen Shot 2020-05-01 at 11 07 33 AM

Is this what's happening here?

**Comment by gadenbuie** [comment]
Basically, `ifelse()` grows the `yes` and `no` answers to that they're the same size as the input using `rep(yes, length.out = length(test)` and then picks the answers from that.

```r
# start with a test and a yes or no answer
test <- c(TRUE, FALSE, TRUE)
yes <- 1:2
no <- 3

# which indices in the test are TRUE and which are FALSE
yes_idx <- which(test) # 1,3
no_idx <- which(!test) # 2

# set up our answer
answer <- test # T, F, T

# Grow the yes and no answers to the length of the test (input)
yes_final <- rep(yes, length.out = length(test)  # 1,2,1
no_final <- rep(no, length.out = length(test))   # 3,3,3

# fill the answer with yes or no from the enlarged yes/no answers
answer[yes_idx] <- yes_final[yes_idx]  # 1, 1
answer[no_idx] <- no_final[no_idx]     # 3

# return our final answer
answer # 1,3,1
```

This is simplified (mangled?) from the [ifelse source code](https://github.com/wch/r-source/blob/22203745de239649317364a5a1dcde4ae438fb2d/src/library/base/R/ifelse.R#L19).

**Comment by MayaGans** [comment]
Holy! That makes sense but it's a freaking whirlwind! Just to _really_ solidify this I ran your second example but with more conditions and "FALSE" instead of 3

`ifelse(c(TRUE, FALSE, TRUE, FALSE, TRUE, TRUE), 1:10, "FALSE")`

Which made it obvious that `ifelse` puts the numbers from `1:10` in the `TRUE` spots based on index and puts "FALSE" string in the `FALSE` spots --- I think I got it now?

**Comment by MayaGans** [comment]
....Also do you mind if I add this discussion and your graphic to the r4ds advanced r bookdown were putting together? 🙏

**Comment by MayaGans** [comment]
@gadenbuie -- using `ifelse(c(TRUE, FALSE, TRUE), 1:3, 4)` I was thinking you may consider using a blue color gradient for `1:3` to show how we're using a sequence for the TRUE and a single value for FALSE? 

Screen Shot 2020-05-01 at 4 43 34 PM

Just an idea though....

**Pull request merged**
