### PR TITLE
Presentation template

### PR DESCRIPTION
**Pull request by kevin-m-kent**
Adding guide that might help first-time presenters. Hoping it will be improved and updated with the input of others.

### CODE REVIEW

**Comment by tanho63** [comment]
Love this idea. Wondering if it should go here or in a dedicated template/package repo instead of into just AdvR!

**Comment by tanho63** [comment]
Some first thoughts: 

- I think I'd reorder practical applications of concepts in order of "easiest-to-hardest" (example functions, own work, shinyapp, r package being the order I think is easiest to hardest). 
- Coming up with guiding questions
- Xaringan spelling ;) 

I think presenter should lead questions about the chapter, not necessarily facilitator, unless presenter is uncomfortable doing so (ie facilitator as fallback)

Xaringan/learnr are nice, maybe would point to template presentations or previous examples.

**Comment by kevin-m-kent** [comment]
Love the suggestions, thanks. Addressed 1, 3, 4. Not sure I understand 2 - do you mean coming up with guidelines for making guiding questions? Or specify that those need to be created by the presenter?

**Comment by tanho63** [comment]
Hah oops. I was thinking that after a few cohorts went through we could come up with/vet a set of guiding topics/questions. I don’t think the thought was fully formed when I wrote that

**Comment by kevin-m-kent** [comment]
Ah gotcha - I think that would be neat as a separate (but related) effort. I think they could be written around @MayaGans 's questions she has collected plus any guiding questions that cohorts have come up with. I'm planning on adding to that Q&A bookdown for my cohort as well.

**Comment by kevin-m-kent** [comment]
Is there an action I need to take here? I see that there are conflicts and that you merged main into this branch. Sorry somewhat new to pull requests.

**Comment by tanho63** [comment]
Ah, sorry! I was debating the right place for this presentation template to live - I think it may be best in https://github.com/tanho63/bookclub-template and linked to the README (so that it can be reused across a few book clubs)

**Comment by kevin-m-kent** [comment]
Ok cool - I kind of screwed up my git history and branches, so let me just delete my forked repo and resubmit this.

**Pull request closed without merging**
